An attempt to create a 3rd IdP with the same issuer was triggering an exception.